apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liveresize.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liveresize.fullname" . }}
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: {{ include "liveresize.fullname" . }} }
subjects:
  - kind: ServiceAccount
    name: {{ include "liveresize.fullname" . }}
    namespace: {{ .Release.Namespace }}
