apiVersion: v1
kind: Service
metadata:
  name: {{ include "liveresize.fullname" . }}
  labels: {{- include "liveresize.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/name: liveresize, app.kubernetes.io/instance: {{ .Release.Name }} }
  ports: [{ name: http, port: 8080, targetPort: http }]
